name: PDS Package build

on:
  push:
    branches:
      - pds-main

jobs:
  build:
    name: Build customized MSAL
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # - name: Free Disk Space (Ubuntu)
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     # this might remove tools that are actually needed,
      #     # when set to "true" but frees about 6 GB
      #     tool-cache: true

      #     # all of these default to true, but feel free to set to
      #     # "false" if necessary for your workflow
      #     android: true
      #     dotnet: false
      #     haskell: true
      #     large-packages: true
      #     swap-storage: true

      - name: Checkout the sourcecode
        uses: actions/checkout@v4
        with:
          set-safe-directory: '*'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@projectdata'

      - run: npm ci
        working-directory: 'lib/msal-common'

      - run: npm ci
        working-directory: 'lib/msal-node'

      - run: node ./gpr.js
        working-directory: 'lib/msal-node'

      - name: Publish
        working-directory: 'lib/msal-node'
        run: npm publish --access=restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
